version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: _docker/web.docker
        volumes:
            - ./:/var/www/html
        ports:
            - "8084:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: _docker/app.docker
        volumes:
            - ./:/var/www/html
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:latest
        environment:
            - "MYSQL_ROOT_PASSWORD=P@55w0rd"
            - "MYSQL_DATABASE=thinkblog"
        ports:
            - "33064:3306"
        volumes:
            - ./_docker/mysql-conf.d:/etc/mysql/conf.d
            - ./_docker/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
